(() => {
const items=[
{id:1,name:'Капучино',category:'coffee',price:240,description:'Эспрессо и нежная молочная пена.',custom:true},
{id:2,name:'Флэт уайт',category:'coffee',price:270,description:'Двойной эспрессо. Чуть меньше молока.',custom:true},
{id:3,name:'Латте',category:'coffee',price:250,description:'Мягкий вкус и бархатная молочная текстура.',custom:true},
{id:4,name:'Айс-латте',category:'cold',price:280,description:'Свежий эспрессо, молоко и много льда.',custom:true},
{id:7,name:'Круассан',category:'bakery',price:190,description:'Хрустящие слои. Сливочное масло.',custom:false},
{id:8,name:'Миндальный',category:'bakery',price:260,description:'Круассан с миндальным кремом.',custom:false},
];
const cart=[];let current=items[0],toastTimer;
const grid=document.getElementById('menu-grid');const drink=document.getElementById('drink');const size=document.getElementById('size'),milk=document.getElementById('milk');
function price(){return current.price+(current.custom?(size.value==='350'?60:0)+(milk.value!=='Обычное'?50:0):0);}
function openItem(id){current=items.find(x=>x.id===id);document.getElementById('drink-title').textContent=current.name;document.getElementById('drink-description').textContent=current.description;document.getElementById('drink-options').hidden=!current.custom;size.value='250';milk.value='Обычное';document.getElementById('drink-price').textContent=price()+' ₽';drink.showModal();}
function renderMenu(category){const list=items.filter(x=>category==='all'||x.category===category);grid.replaceChildren();list.forEach(item=>{
const article=document.createElement('article');article.className='menu-card';article.innerHTML='<div class="drink-art '+item.category+'" aria-hidden="true"><img src="../assets/'+(item.category==='cold'?'mori-cold':item.category==='bakery'?'mori-bakery':'mori-hot')+'.webp" alt="" loading="lazy"></div><div class="card-top"><h3></h3><span></span></div><p></p><button type="button">Выбрать <span>+</span></button>';article.querySelector('h3').textContent=item.name;article.querySelector('.card-top span').textContent=item.price+' ₽';article.querySelector('p').textContent=item.description;article.querySelector('button').setAttribute('aria-label','Выбрать '+item.name);article.querySelector('button').addEventListener('click',()=>openItem(item.id));grid.append(article);});document.getElementById('menu-status').textContent='Показано позиций: '+list.length+'.';if(window.gsap&&!matchMedia('(prefers-reduced-motion: reduce)').matches)gsap.from(grid.children,{y:18,opacity:0,stagger:.035,duration:.4});}
document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(x=>x.setAttribute('aria-pressed',String(x===button)));renderMenu(button.dataset.category);}));
[size,milk].forEach(select=>select.addEventListener('change',()=>document.getElementById('drink-price').textContent=price()+' ₽'));
function renderCart(){document.getElementById('basket-count').textContent=cart.length;const list=document.getElementById('basket-items');list.replaceChildren();if(!cart.length){const p=document.createElement('p');p.textContent='Пока здесь пусто. Выберите что-нибудь по настроению.';list.append(p);}cart.forEach((item,index)=>{const row=document.createElement('div');row.className='basket-row';row.innerHTML='<div><strong></strong><small></small></div><span></span><button>Убрать</button>';row.querySelector('strong').textContent=item.name;row.querySelector('small').textContent=item.options;row.querySelector('span').textContent=item.price+' ₽';row.querySelector('button').setAttribute('aria-label','Убрать '+item.name);row.querySelector('button').addEventListener('click',()=>{cart.splice(index,1);renderCart();});list.append(row);});document.getElementById('basket-total').textContent=cart.length?'Итого в демонстрационном выборе: '+cart.reduce((s,x)=>s+x.price,0)+' ₽':'';}
document.getElementById('drink-form').addEventListener('submit',event=>{event.preventDefault();cart.push({name:current.name,price:price(),options:current.custom?size.value+' мл · '+milk.value:'Стандартная порция'});renderCart();drink.close();const toast=document.getElementById('toast');toast.textContent=current.name+' добавлен в ваш выбор';toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),2500);});
const brews={filter:{title:'Чашка с ясным вкусом.',copy:'Смочите бумажный фильтр. Налейте немного воды на кофе, дайте ему раскрыться, затем медленно добавляйте оставшуюся воду круговыми движениями.',values:['18 г','300 мл','3 минуты'],labels:['кофе среднего помола','вода 92–96 °C','ориентир по времени']},turk:{title:'Тихое утро у плиты.',copy:'Используйте мелкий помол. Смешайте кофе с водой в турке и нагревайте на слабом огне. Снимите, когда начнёт подниматься пена, не доводя до кипения.',values:['10 г','100 мл','4 минуты'],labels:['кофе тонкого помола','холодная вода','ориентир по времени']},press:{title:'Плотно. Просто. Без спешки.',copy:'Залейте крупно смолотый кофе горячей водой. Дайте настояться, аккуратно размешайте и медленно опустите поршень. Сразу перелейте кофе в чашку.',values:['20 г','300 мл','4 минуты'],labels:['кофе крупного помола','вода 92–96 °C','время настаивания']}};
function renderBrew(key){const b=brews[key];const panel=document.getElementById('brew-info');panel.innerHTML='<h3></h3><p></p><div class="brew-measures"></div>';panel.querySelector('h3').textContent=b.title;panel.querySelector('p').textContent=b.copy;b.values.forEach((value,i)=>{const div=document.createElement('div');const num=document.createElement('b'),label=document.createElement('span');num.textContent=value;label.textContent=b.labels[i];div.append(num,label);panel.querySelector('.brew-measures').append(div);});}
document.querySelectorAll('[data-brew]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-brew]').forEach(x=>x.setAttribute('aria-pressed',String(x===button)));renderBrew(button.dataset.brew);}));
renderMenu('all');renderCart();renderBrew('filter');
if(window.gsap&&!matchMedia('(prefers-reduced-motion: reduce)').matches){gsap.from('.floating-cup',{y:45,rotation:8,scale:.9,duration:1.3,ease:'power3.out'});gsap.from('.hero-sticker',{y:35,rotation:3,duration:1.1,delay:.2,ease:'power3.out'});gsap.to('.floating-cup',{y:45,rotation:-16,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.to('.word-band div',{xPercent:-20,ease:'none',scrollTrigger:{trigger:'.word-band',start:'top bottom',end:'bottom top',scrub:1}});gsap.to('.closing-star',{rotation:90,ease:'none',scrollTrigger:{trigger:'.closing',start:'top bottom',end:'bottom top',scrub:1}});}
})();
