(() => {
  let pairKey='classic',tasteKey='soft';
  const pairs={classic:{ids:[1,7],title:'Капучино + круассан',copy:'Мягкая молочная пена и хрустящие сливочные слои. Для спокойного начала дня.',image:'mori-hot'},bold:{ids:[2,7],title:'Флэт уайт + круассан',copy:'Выразительный кофейный характер и спокойная сливочная пара. Когда хочется почувствовать кофе.',image:'mori-hot'},cold:{ids:[4,8],title:'Айс-латте + миндальный',copy:'Прохладный напиток, лёд и миндальный крем. Для более свежего и сладкого настроения.',image:'mori-cold'}};
  document.querySelectorAll('[data-m-pair]').forEach(button=>button.addEventListener('click',()=>{pairKey=button.dataset.mPair;const pair=pairs[pairKey];document.querySelectorAll('[data-m-pair]').forEach(other=>other.setAttribute('aria-pressed',String(other===button)));document.getElementById('m-pair-title').textContent=pair.title;document.getElementById('m-pair-copy').textContent=pair.copy;document.getElementById('m-pair-image').src='../assets/'+pair.image+'.webp';document.getElementById('m-pair-status').textContent='Демонстрационный выбор из меню. Без оформления заказа.';document.dispatchEvent(new CustomEvent('mori:pair-preview',{detail:pair.ids}));if(window.gsap&&!matchMedia('(prefers-reduced-motion: reduce)').matches)gsap.fromTo('.m-pair-cup',{y:18,rotation:-3,scale:.96},{y:0,rotation:-8,scale:1,duration:.8,ease:'back.out(1.3)',overwrite:true});}));
  document.getElementById('m-add-pair').addEventListener('click',()=>document.dispatchEvent(new CustomEvent('mori:add-pair',{detail:pairs[pairKey].ids})));
  const tastes={soft:{id:3,name:'Латте',copy:'Молоко смягчает вкус кофе и делает напиток спокойным, округлым и знакомым.',coffee:40,milk:85,image:'mori-hot',alt:'Молочный кофейный напиток'},bold:{id:2,name:'Флэт уайт',copy:'Более выраженный кофейный характер. Молоко дополняет вкус, сохраняя ему главную роль.',coffee:85,milk:50,image:'mori-hot',alt:'Молочный кофе с выразительным вкусом'},fresh:{id:4,name:'Айс-латте',copy:'Эспрессо, молоко и лёд. Знакомый кофейный вкус в более прохладной подаче.',coffee:55,milk:70,image:'mori-cold',alt:'Холодный айс-латте со льдом'}};
  document.querySelectorAll('[data-m-taste]').forEach(button=>button.addEventListener('click',()=>{tasteKey=button.dataset.mTaste;const data=tastes[tasteKey];document.querySelectorAll('[data-m-taste]').forEach(other=>other.setAttribute('aria-pressed',String(other===button)));document.getElementById('m-taste-name').textContent=data.name;document.getElementById('m-taste-copy').textContent=data.copy;document.getElementById('m-taste-coffee').style.width=data.coffee+'%';document.getElementById('m-taste-milk').style.width=data.milk+'%';const image=document.getElementById('m-taste-image');image.src='../assets/'+data.image+'.webp';image.alt=data.alt;if(window.gsap&&!matchMedia('(prefers-reduced-motion: reduce)').matches)gsap.fromTo(image,{x:20,rotation:-4},{x:0,rotation:-10,duration:.65,ease:'power3.out',overwrite:true});}));
  document.getElementById('m-taste-open').addEventListener('click',()=>document.dispatchEvent(new CustomEvent('mori:open-item',{detail:tastes[tasteKey].id})));
  if(!window.gsap||!window.ScrollTrigger)return;
  gsap.matchMedia().add('(prefers-reduced-motion: no-preference)',()=>{gsap.fromTo('.m-pair-bakery',{y:-15,rotation:0},{y:15,rotation:13,ease:'none',scrollTrigger:{trigger:'.m-pair',start:'top bottom',end:'bottom top',scrub:1.2}});gsap.to('.m-pair-spark',{rotation:100,ease:'none',scrollTrigger:{trigger:'.m-pair',start:'top bottom',end:'bottom top',scrub:1}});gsap.to('.m-taste-star',{rotation:-75,ease:'none',scrollTrigger:{trigger:'.m-taste',start:'top bottom',end:'bottom top',scrub:1}});gsap.fromTo('.m-place-tag',{rotation:1,y:12},{rotation:6,y:-12,ease:'none',scrollTrigger:{trigger:'.m-place-photo',start:'top bottom',end:'bottom top',scrub:1}});});
})();
