(() => {
const menu=document.querySelector('.menu-button'),nav=document.getElementById('navigation');function closeMenu(){nav.classList.remove('is-open');menu.setAttribute('aria-expanded','false');}menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('is-open',open);menu.setAttribute('aria-expanded',String(open));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const cases={donuts:{title:'39 Donuts',description:'Редизайн рекламного лендинга франшизы. Самостоятельная работа над визуальным направлением, структурой и реализацией.',role:'Полностью разработал новый дизайн и сайт без участия других дизайнеров и разработчиков.',status:'В портфолио показана демонстрация редизайна. Коммерческий запуск не заявляется.',url:'https://developer-48.github.io/39donuts-franchise-concept-demo/'},kf21:{title:'KF21 — публичный лендинг',description:'Сайт образовательного проекта, реализованный с нуля по предоставленному дизайн-макету.',role:'Выполнил фронтенд-реализацию всего лендинга, адаптивную вёрстку и собственные визуальные доработки.',status:'Показан только публичный сайт. Опыт разработки личных кабинетов описан в разделе бизнес-систем.',url:'https://kf21.ru/'}};
const dialog=document.getElementById('case-dialog');document.querySelectorAll('[data-case]').forEach(button=>button.addEventListener('click',()=>{const c=cases[button.dataset.case];document.getElementById('case-title').textContent=c.title;document.getElementById('case-description').textContent=c.description;document.getElementById('case-role').textContent=c.role;document.getElementById('case-status').textContent=c.status;document.getElementById('case-link').href=c.url;dialog.showModal();}));document.getElementById('close-case').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});
if(window.gsap&&window.ScrollTrigger){gsap.registerPlugin(ScrollTrigger);gsap.matchMedia().add('(prefers-reduced-motion: no-preference)',()=>{
gsap.from('.headline-line',{yPercent:80,opacity:0,stagger:.11,duration:1.15,ease:'power4.out'});gsap.from('.hero-description,.hero-copy>.primary',{y:20,opacity:0,stagger:.1,delay:.4,duration:.8,ease:'power3.out'});
document.querySelectorAll('[data-reveal]').forEach(el=>gsap.from(el,{y:35,opacity:0,duration:.8,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 92%',once:true}}));
document.querySelectorAll('[data-image-reveal]').forEach(el=>{gsap.from(el,{clipPath:'inset(10% 0 10% 0)',duration:1.25,ease:'power3.inOut',scrollTrigger:{trigger:el,start:'top 90%',once:true}});const img=el.querySelector('img');if(el.classList.contains('concept-preview'))gsap.fromTo(img,{scale:1.08,yPercent:-3},{scale:1,yPercent:3,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:1}});});
document.querySelectorAll('[data-magnetic]').forEach(el=>{const move=e=>{if(!matchMedia('(pointer:fine)').matches)return;const r=el.getBoundingClientRect();gsap.to(el,{x:(e.clientX-r.left-r.width/2)*.1,y:(e.clientY-r.top-r.height/2)*.1,duration:.3});};const leave=()=>gsap.to(el,{x:0,y:0,duration:.7,ease:'elastic.out(1,.45)'});el.addEventListener('pointermove',move);el.addEventListener('pointerleave',leave);});
});gsap.to('.reading-line',{scaleX:1,ease:'none',scrollTrigger:{start:0,end:'max',scrub:true}});document.fonts.ready.then(()=>ScrollTrigger.refresh());}
const reduce=matchMedia('(prefers-reduced-motion: reduce)');if(!reduce.matches&&matchMedia('(pointer:fine)').matches){import('./ink.js').then(module=>module.initInk()).catch(()=>{});}
})();
