(() => {
  let sceneKey='evening';
  const scenes={evening:{number:'01 / Локальный свет',title:'ВЕЧЕР\nБЕЗ СПЕШКИ.',copy:'Небольшой столик, любимое кресло и мягкое свечение рядом. AMBER добавляет комнате спокойный световой акцент.',model:'amber',name:'AMBER'},table:{number:'02 / Общая точка',title:'ВСТРЕТИТЬСЯ\nЗА СТОЛОМ.',copy:'Горизонтальная линия над столом собирает пространство вокруг встречи. LINE поддерживает форму стола, оставляя интерьер открытым.',model:'line',name:'LINE'},reading:{number:'03 / Личная пауза',title:'ЕЩЁ ОДНА\nГЛАВА.',copy:'Кресло, книга и отдельный источник рядом. ARC обозначает тихий уголок, не забирая внимание у остальной комнаты.',model:'arc',name:'ARC'}};
  document.querySelectorAll('[data-l-scene]').forEach(button=>button.addEventListener('click',()=>{sceneKey=button.dataset.lScene;const data=scenes[sceneKey];document.querySelectorAll('[data-l-scene]').forEach(other=>other.setAttribute('aria-pressed',String(other===button)));document.querySelectorAll('[data-l-scene-image]').forEach(image=>{const active=image.dataset.lSceneImage===sceneKey;image.classList.toggle('is-active',active);image.setAttribute('aria-hidden',String(!active));});document.getElementById('l-scene-number').textContent=data.number;document.getElementById('l-scene-title').textContent=data.title;document.getElementById('l-scene-copy').textContent=data.copy;const more=document.getElementById('l-scene-more');more.firstChild.textContent='О светильнике '+data.name+' ';more.setAttribute('aria-label','О светильнике '+data.name);}));
  document.getElementById('l-scene-more').addEventListener('click',()=>document.querySelector('[data-product="'+scenes[sceneKey].model+'"]').click());
  document.querySelectorAll('[data-l-detail]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-l-detail]').forEach(other=>other.setAttribute('aria-pressed',String(other===button)));document.querySelectorAll('[data-l-detail-copy]').forEach(copy=>copy.classList.toggle('is-active',copy.dataset.lDetailCopy===button.dataset.lDetail));}));
  if(!window.gsap||!window.ScrollTrigger)return;
  gsap.matchMedia().add('(prefers-reduced-motion: no-preference)',()=>{gsap.fromTo('.l-detail-photo>img',{rotation:-3,y:15},{rotation:3,y:-15,ease:'none',scrollTrigger:{trigger:'.l-material',start:'top bottom',end:'bottom top',scrub:1.3}});gsap.fromTo('.l-guide-rule',{scaleX:.25},{scaleX:1,ease:'none',scrollTrigger:{trigger:'.l-light-guide',start:'top 85%',end:'top 35%',scrub:1}});gsap.fromTo('.l-scale-drawing svg',{y:15},{y:-5,ease:'none',scrollTrigger:{trigger:'.l-scale-grid',start:'top bottom',end:'bottom top',scrub:1}});const stage=document.querySelector('.l-scene-stage');const move=event=>{if(event.pointerType==='touch')return;const box=stage.getBoundingClientRect();stage.style.setProperty('--scene-x',(event.clientX-box.left)+'px');stage.style.setProperty('--scene-y',(event.clientY-box.top)+'px');};stage.addEventListener('pointermove',move,{passive:true});return()=>stage.removeEventListener('pointermove',move);});
})();
